open::with args
Byron/open-rs pull request #62
Opened 2023-02-01 12:57 UTC by benjajaja

`open::with(path, "firefox --new-window --more-flags")` primitively passes the args to `Command`. Primitively, because `String::split_whitespace` might not be good enough. There is a crate
[shell-words](https://crates.io/crates/shell-words) that would do the right thing, but I don't want to bring in a dependency unless asked.

2023-02-02 06:28 UTC, Byron requested changes
This seems like a worth-while addition, thanks for proposing it.

Since the new behaviour of string-splitting is only implemented for a single platform and is nothing I'd expect, I wonder if this should rather be behind a new function name that takes `app` and `args` separately. I'd really not want to encourage anybody to join strings just to satisfy API constraints that were made without this case in mind.

Implementing such a new function correctly of course is more effort, as it would probably need internal changes to actually work for every platform and it feels wrong to only release it for a single one.

The other popular 'open' crate, `opener` also doesn't seem to support this, and I don't know if it would be easier to implement such a feature there. CC @Seeker14491, the author of `opener` who also chimed in here a couple of times.

2023-02-02 08:20 UTC, benjajaja commented
I forgot to clarify: current behaviour (on unix) of `with` only works if the argument is a single word. That is: `Command::new("firefox --new-window").arg(<path-to-open>).spawn()` fails with something like `No such file or directory`.

Splitting the string is backwards compatible and only enables the option to also use `prog --with args`.

My use case is actually the opposite of joining strings. By default, I use `that`. The user may set a setting to open with a specific command though, and then I use `with`. That setting would just be a string, and not a list of strings with a minimum length of 1.

2023-02-02 15:37 UTC, Byron commented
Thanks for the clarification.

> Splitting the string is backwards compatible and only enables the option to also use prog --with args

I think that's not the case if applications are passed by full path, and that contains a space. Even though not common, it's not unusual enough to me to break it with an alternative option available.

> My use case is actually the opposite of joining strings. By default, I use that. The user may set a setting to open with a specific command though, and then I use with. That setting would just be a string, and not a list of strings with a minimum length of 1.

It seems like a method that supporting arguments would cover your case better, as `args` could be empty until the user indicates it otherwise.

2023-02-02 16:10 UTC, benjajaja commented
Ah, spaces in the path, I didn't think of that.
I will make a `with_args` then.

2023-03-06 10:22 UTC, Byron commented
With the latest release and the addition of `with_command()`, it's possible to add arguments before spawning the launcher, which is more general than the method proposed here.

[Here is the new release](https://github.com/Byron/open-rs/releases/tag/v3.4.0).

2023-03-06 10:22 UTC, closed without merging