feat: add command function to return std::Command
Byron/open-rs pull request #64
Opened 2023-02-05 18:17 UTC by matoous

Adds new `command` function that returns the underlying `std::Command` that would be called to open given path.

Related: https://github.com/Byron/open-rs/pull/63
Related: https://github.com/helix-editor/helix/pull/5820

2023-02-05 18:58 UTC, Byron requested changes
Thanks for giving it a shot!

Instead of trying `--version` in various programs, I think it's better to try to execute them. That way, `Command` tells you if it could find an executable by that name by erroring when trying to launch it, or not. This assumes these programs don't have a side-effect when launched like that which I believe _should_ be the case. That, however, definitely needs validation. 

Once a program is found, one *could* cache this information statically, but then again, we didn't do that previously and can probably just keep everything pure and simple. In the worst case, we would probably waste 40ms to find a program that works, which seems quite alright.

2023-02-05 21:51 UTC, matoous commented
@Byron done. Any recommendations for how to easily fix this for someone who runs solely on macos devices? I could spin up a few VMs but maybe there's easier way?

2023-02-05 23:50 UTC, pascalkuthe commented
I think we actually should neither call version or execute the command in anyway. Instead we should just return a vec of commands that can be executed by the calle until one of then works.

Calling any command in anyway is a blocking operation and should not be done unless explicitly requested.

2023-02-06 06:34 UTC, Byron commented
> @Byron done. Any recommendations for how to easily fix this for someone who runs solely on macos devices? I could spin up a few VMs but maybe there's easier way?

I am using Parallels for that, and am not aware of an easier way except for using CI, but that has its own drawbacks. Once the API is finalized I am happy to help test it on some linux VMs I have available, and windows as well.

2023-02-06 06:38 UTC, Byron commented
> I think we actually should neither call version or execute the command in anyway. Instead we should just return a vec of commands that can be executed by the calle until one of then works.
> 
> Calling any command in anyway is a blocking operation and should not be done unless explicitly requested.

Fair enough! 

Let's not return a `Vec` though, but an `impl Iterator<Item = std::process::Command>` instead to save an allocation. This also means the 'multi-command' logic can now be used by all platforms, as it works similarly with just a single command.

2023-02-06 06:50 UTC, Byron requested changes
Thanks a lot for getting this work started!

I have added a few localized comments which I hope are helpful.

2023-02-06 06:50 UTC, Byron commented on src/haiku.rs
> +    command(path).status_without_output().into_result()
I think this `CommandExt` method should be split into two, so the configuration of IO channels is separate from executing it.

Thus, future invocations would look more like this:

```Rust
Command::new(…).without_io().status().into_result()
```

2023-02-06 06:50 UTC, Byron commented on src/ios.rs
> +pub fn command<T: AsRef<OsStr>>(path: T) -> Command {
The signature here could be 

```suggestion
pub fn commands<T: AsRef<OsStr>>(path: T) -> impl Iterator<Item = Command> {
```

Note that `Option` implements `Iterator`, so single-commands can be wrapped in an option when returning them.

2023-02-06 06:50 UTC, Byron commented on src/lib.rs
> +/// Get command that opens path with the default application.
I think it should be mentioned that this is a 'no-run' sibling of `open::that(…)`, as opposed to, say, `open::with(…)`.

2023-03-06 10:01 UTC, Byron commented
I am closing this (somewhat stalled) PR in favor of #66 which incorporates some changes from this PR while rounding out the new `Command` based API.

The reason for my sudden activity is #65 which made me think that this PR actually contains a solution already, so I'd like to see it come to completion now once and and for all.

Thanks for everybody involved - and thanks to `helix` which consistently pushes some of my crates to new heights :).

2023-03-06 10:01 UTC, closed without merging

2023-03-06 10:28 UTC, Byron commented
The [new release is now available](https://github.com/Byron/open-rs/releases/tag/v3.4.0).