feat: these for several path
Byron/open-rs pull request #78
Opened 2023-05-11 20:14 UTC by Mehrbod2002

2023-05-12 08:30 UTC, Byron requested changes
The idea of `these` would be to pass multiple paths to `commands()` at once. What makes this hard isn't the API though, it's validating that it even makes sense for the launchers that are offered on each platform. Not all of them may support multiple paths at all, which is when one would have to let it fall back to launching each command individually.

Besides that, any use of `unsafe` is unacceptable  here and also not required. Instead of `PathIter`, try to use something like `impl IntoIterator<Item = impl AsRef<OsStr>>` or the version with explicit type constraints using `where I: IntoIterator<Item = R>, R: AsRef<OsStr>`, you will probably have to fiddle with lifetimes a bit.

2023-05-12 08:37 UTC, Mehrbod2002 commented
@Byron 
To be sure , multi path means open a browser with different path on different tabs ?

2023-05-12 08:48 UTC, Byron commented
I think it means that launchers who can take multiple paths at once can be provided with multiple paths. The effect of this is defined by its implementation.

2023-05-13 04:06 UTC, Mehrbod2002 commented
@Byron 
I think there is a misunderstanding about this impl . the command with several means open an browser with multi path in multi tabs ?

2023-05-13 07:49 UTC, Byron reviewed
Thanks for trying to contribute!

However, it seems there is difficulty in communication and/or understanding, which is why I would prefer abandoning this PR instead of trying to push it into shape. My time is too scarce to be able to engage here.

Thanks for your understanding.

2023-05-13 07:49 UTC, Byron commented on src/lib.rs
> +    path: impl IntoIterator<Item = impl AsRef<OsStr>> + std::convert::AsRef<std::ffi::OsStr>,
There is no need for any function that can be emulated with `for path in paths { open::that(path)?; }` Instead, in order to implement it as described in #70, launchers must be fed multiple paths if they support it.

2023-05-13 07:49 UTC, closed without merging